server:
  port: 8888
  address: 0.0.0.0
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/*
    username: *
    password: *

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true